### ISSUE TITLE
关于token_hold那一节

### ISSUE THREAD

**Issue by xiadd** [swfbarhr/blog#6]
> 求B就会认为access_token已过期，也会同请求A一样，去微信服务器请求新的access_token，这样就会导致请求A得到的access_token失效。

这段文字是否经过考证？

根据微信平台文档所说："在刷新过程中，中控服务器对外输出的依然是老access_token，此时公众平台后台会保证在刷新短时间内，新老access_token都可用，这保证了第三方业务的平滑过渡。"

我自己经过测试也是新老token都是有效的。当然短时间具体是多少就不知道了

**Comment by swfbarhr** [comment]
如果按时间来的话，大概10min到20min。如果是次数的话，大概在7-10次左右。

**Comment by swfbarhr** [comment]
我也承认，微信官方给出的方法是最适合的，但是基于各种因素，我这边暂时不能跑多个程序，基于这个原因，我才对access_token维持做了如上的探索，纯属个人思考而已

**Comment by xiadd** [comment]
确实，肯定根据实际情况来的，我只是对这边有点疑问
